project/blog/urls.py
from django.urls import path
from blog import views as blog_views

app_name = 'blog'
urlpatterns = [
    path('', blog_views.index, name='question-index'),
    path('permission_denied/', blog_views.permission_denied, name='permission-denied'),
    path('question/ask', blog_views.QuestionAskView.as_view(), name='question-ask'),
    path('question/<int:question_id>/detail', blog_views.detail, name='question-detail'),
    path('question/<int:question_id>/edit', blog_views.QuestionEditView.as_view(), name='question-edit'),
    path('question/<int:question_id>/delete', blog_views.QuestionDeleteView.as_view(), name='question-delete'),
    path('question/<int:question_id>/answer/add', blog_views.AnswerAddView.as_view(), name='answer-add'),
    path('question/<int:question_id>/answer/<int:answer_id>/edit', blog_views.AnswerEditView.as_view(), name='answer-edit'),
    path('question/<int:question_id>/answer/<int:answer_id>/delete', blog_views.AnswerDeleteView.as_view(), name='answer-delete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('blog.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path
from user import views as user_views

app_name = 'user'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('<int:user_id>/profile/', user_views.profile, name='profile'),
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout')
]

project/project/templates/project/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question and Answer Platform</title>

    <meta name="description" content="A platform for talking about programming.">
    <meta name="keywords", content="C, C++, C#, Go, Python, MQL, HTML, CSS, JavaScript">

    <link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'user/style.css' %}">
</head>
<body>
    <nav class="nav-bar">
        <ul>
            <div class="nav-bar-left">
                <li><a href="{% url 'blog:question-index' %}">Home</a></li>
                <li><a href="#">About Us</a></li>
            </div>
            <div class="nav-bar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'user:logout' %}">Logout</a></li>
                    <li><a href="{% url 'user:profile' request.user.id %}">Profile</a></li>
                    <li><a href="{% url 'blog:question-ask' %}">Ask Question</a></li>            
                {% else %}
                    <li><a href="{% url 'user:login' %}">Login</a></li>
                    <li><a href="{% url 'user:register' %}">Register</a></li>
                {% endif %}
            </div>               
        </ul>
    </nav>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <script src="{% static 'user/profile.js' %}"></script>
</body>
</html>