project/blog/urls.py
from django.urls import path
from blog import views as blog_views

app_name = 'blog'
urlpatterns = [
    path('', blog_views.index, name='question-index'),
    path('permission_denied/', blog_views.permission_denied, name='permission-denied'),
    path('question/ask', blog_views.QuestionAskView.as_view(), name='question-ask'),
    path('question/<int:question_id>/detail', blog_views.detail, name='question-detail'),
    path('question/<int:question_id>/edit', blog_views.QuestionEditView.as_view(), name='question-edit'),
    path('question/<int:question_id>/delete', blog_views.QuestionDeleteView.as_view(), name='question-delete'),
    path('question/<int:question_id>/answer/add', blog_views.AnswerAddView.as_view(), name='answer-add'),
    path('question/<int:question_id>/answer/<int:answer_id>/edit', blog_views.AnswerEditView.as_view(), name='answer-edit'),
    path('question/<int:question_id>/answer/<int:answer_id>/delete', blog_views.AnswerDeleteView.as_view(), name='answer-delete'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('blog.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path
from user import views as user_views

app_name = 'user'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('<int:user_id>/profile/', user_views.profile, name='profile'),
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout')
]

project/blog/models.py
from django.db import models as db_models
from django.contrib.auth import models as auth_models


class Question(db_models.Model):
    author = db_models.ForeignKey(auth_models.User, on_delete=db_models.CASCADE)

    title = db_models.CharField(max_length=200)
    body = db_models.TextField()
    published = db_models.DateTimeField(auto_now_add=True)
    updated = db_models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Answer(db_models.Model):
    author = db_models.ForeignKey(auth_models.User, on_delete=db_models.CASCADE)
    question = db_models.ForeignKey(Question, on_delete=db_models.CASCADE)

    body = db_models.TextField()
    published = db_models.DateTimeField(auto_now_add=True)
    updated = db_models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'answer by {self.author}'

project/blog/views.py
from django.contrib.auth import mixins
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.urls import reverse
from blog import models as blog_models


def permission_denied(request):
    context = request.session['permission_denied']
    template = 'blog/permission_denied.html'
    return render(request, template, context)


def index(request):
    questions_list = blog_models.Question.objects.order_by('-published')
    context = {
        'questions_list': questions_list
    }
    template = 'blog/index.html'
    return render(request, template, context)


def detail(request, question_id):
    question = get_object_or_404(blog_models.Question, pk=question_id)
    answers = question.answer_set.order_by('-published').all()
    context = {
        'question': question,
        'answers': answers
    }
    template = 'blog/detail.html'
    return render(request, template, context)


class QuestionAskView(mixins.LoginRequiredMixin, generic.CreateView):
    model = blog_models.Question
    template_name = 'blog/question_ask.html'
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_ask_edit_form'] = context.pop('form')
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        context = {'question_id': self.object.id}
        return reverse('blog:question-detail', kwargs=context)


class QuestionEditView(mixins.UserPassesTestMixin, generic.UpdateView):
    model = blog_models.Question
    template_name = 'blog/question_edit.html'
    pk_url_kwarg = 'question_id'
    fields = ['title', 'body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_ask_edit_form'] = context.pop('form')
        context['question'] = context.pop('object')
        return context

    def get_success_url(self):
        context = {'question_id': self.object.id}
        return reverse('blog:question-detail', kwargs=context)

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        return False

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            self.request.session['permission_denied'] = {'model': 'question', 'operation': 'edit'}
            return redirect('blog:permission-denied')
        else:
            redirect_url = f"{reverse('user:login')}?next={self.request.path}"
            return redirect(redirect_url)


class QuestionDeleteView(mixins.UserPassesTestMixin, generic.DeleteView):
    model = blog_models.Question
    template_name = 'blog/question_delete.html'
    pk_url_kwarg = 'question_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['question_delete_form'] = context.pop('form')
        context['question'] = context.pop('object')
        return context

    def get_success_url(self):
        return reverse('blog:question-index')

    def test_func(self):
        question = self.get_object()
        if self.request.user == question.author:
            return True
        return False

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            self.request.session['permission_denied'] = {'model': 'question', 'operation': 'delete'}
            return redirect('blog:permission-denied')
        else:
            redirect_url = f"{reverse('user:login')}?next={self.request.path}"
            return redirect(redirect_url)

    
class AnswerAddView(mixins.LoginRequiredMixin, generic.CreateView):
    model = blog_models.Answer
    template_name = 'blog/answer_add.html'
    pk_url_kwarg = 'question_id'
    fields = ['body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_add_form'] = context.pop('form')
        question = get_object_or_404(blog_models.Question, pk=self.kwargs.get('question_id'))
        answers = question.answer_set.order_by('-published').all()
        context.update({'question': question, 'answers': answers})
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.question = get_object_or_404(blog_models.Question, pk=self.kwargs.get('question_id'))
        return super().form_valid(form)

    def get_success_url(self):
        context = {'question_id': self.kwargs.get('question_id')}
        return reverse('blog:question-detail', kwargs=context)


class AnswerEditView(mixins.UserPassesTestMixin, generic.UpdateView):
    model = blog_models.Answer
    template_name = 'blog/answer_edit.html'
    pk_url_kwarg = 'answer_id'
    fields = ['body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_edit_form'] = context.pop('form')
        question = get_object_or_404(blog_models.Question, pk=self.kwargs.get('question_id'))
        answers = question.answer_set.order_by('-published').all()
        context.update({'question': question, 'answers': answers, 'answer_selected': self.get_object()})
        return context

    def get_success_url(self):
        context = {'question_id': self.kwargs.get('question_id')}
        return reverse('blog:question-detail', kwargs=context)

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.author:
            return True
        return False

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            self.request.session['permission_denied'] = {'model': 'answer', 'operation': 'edit'}
            return redirect('blog:permission-denied')
        else:
            redirect_url = f"{reverse('user:login')}?next={self.request.path}"
            return redirect(redirect_url)


class AnswerDeleteView(mixins.UserPassesTestMixin, generic.DeleteView):
    model = blog_models.Answer
    template_name = 'blog/answer_delete.html'
    pk_url_kwarg = 'answer_id'
    fields = ['body']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answer_delete_form'] = context.pop('form')
        question = get_object_or_404(blog_models.Question, pk=self.kwargs.get('question_id'))
        answers = question.answer_set.order_by('-published').all()
        context.update({'question': question, 'answers': answers, 'answer_selected': self.get_object()})
        return context
    
    def get_success_url(self):
        context = {'question_id': self.kwargs.get('question_id')}
        return reverse('blog:question-detail', kwargs=context)

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.author:
            return True
        return False

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            self.request.session['permission_denied'] = {'model': 'answer', 'operation': 'delete'}
            return redirect('blog:permission-denied')
        else:
            redirect_url = f"{reverse('user:login')}?next={self.request.path}"
            return redirect(redirect_url)

project/blog/templates/blog/answer_add.html
{% extends "blog/detail.html" %}
{% load form_tags_filters %}

{% block answer_add_form %}
    <form class="form" style="width: inherit" id="answer-add-form" action="{% url 'blog:answer-add' question.id %}" method="post">
        {% csrf_token %}
        <ul>
            {% for field in answer_add_form %}
                {% with field=field|label_suffix:'' %}
                    <li>
                        {% with field=field|label:'Answer' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Write your answer' }}
                        {% endwith %}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <div class="help-text">{{ field.help_text }}</div>
                        {% endif %}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
        <div class="form-buttons">
            <input class="button" type="submit" value="Post">
            <a href="{% url 'blog:question-detail' question.id %}" class="button" id="hide-answer-add-form-button">Cancel</a>
        </div>
    </form>
{% endblock answer_add_form %}

project/blog/templates/blog/answer_delete.html
{% extends "blog/detail.html" %}
{% load form_tags_filters %}

{% block answer_delete_form %}
    {% if answer.id == answer_selected.id %}
        <form class="form" style="width: inherit; margin: 0.5rem 0rem; padding: 0.5rem 1rem; background-color: moccasin;" action="{% url 'blog:answer-delete' question.id answer.id %}" method="post">
            {% csrf_token %}
            <h4 class="form-title">Are you sure that you want to delete the above answer?</h4>
            <div class="form-buttons">
                <input class="button" type="submit" value="Delete">
                <a class="button" href="{% url 'blog:question-detail' question.id %}">Cancel</a> 
            </div>
        </form>
    {% endif %}
{% endblock answer_delete_form %}

project/blog/templates/blog/answer_edit.html
{% extends "blog/detail.html" %}
{% load form_tags_filters %}

{% block answer_edit_form %}
    {% if answer.id == answer_selected.id %}
        <form class="form" style="width: inherit; margin: 0rem; margin-bottom: 0.75rem;" id="answer-edit-form" action="{% url 'blog:answer-edit' question.id answer.id %}" method="post">
            {% csrf_token %}
            <ul>
                {% for field in answer_edit_form %}
                    {% with field=field|label_suffix:'' %}
                        <li>
                            {% with field=field|label:'Edit Answer' %}
                                {{ field.label_tag }}
                                {{ field }}
                            {% endwith %}
                            {{ field.errors }}
                            {% if field.help_text %}
                                <div class="help-text">{{ field.help_text }}</div>
                            {% endif %}
                        </li>
                    {% endwith %}
                {% endfor %}
            </ul>
            <div class="form-buttons">
                <input class="button" type="submit" value="Update">
                <a href="{% url 'blog:question-detail' question.id %}" class="button" id="hide-answer-edit-form-button">Cancel</a>
            </div>
        </form>
    {% endif %}
{% endblock answer_edit_form %}

project/blog/templates/blog/ask.html
{% extends "project/base.html" %}
{% load form_tags_filters %}

{% block content %}
    <form class="form" action="{% url 'blog:question-ask' %}" method="post">
        {% csrf_token %}
        <h2 class="form-title">Ask a New Question</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <ul>
            {% for field in question_ask_edit_form %}
                {% with field=field|label_suffix:'' %}
                    <li>
                        {% if field.id_for_label == 'id_title' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Choose a title for your question' }}
                        {% elif field.id_for_label == 'id_body' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Write your question' }}
                        {% endif %}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <div class="help-text">{{ field.help_text }}</div>
                        {% endif %}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
        <div class="form-buttons">
            <input class="button" type="submit" value="Post">
        </div>
    </form>
{% endblock content %}

project/blog/templates/blog/delete.html
{% extends "project/base.html" %}

{% block content %}
    <ul class="questions-list">
        <li class="question-card">
            <h2 class="question-title">{{ question.title }}</h2>
            <p class="question-body-preview">{{ question.body }}</p>
            <ul class="question-info">
                <div>
                    <li>asked by <span class="question-author">{{ question.author }}</span> on {{ question.published|date:"F d, Y" }} at {{ question.published|date:"H:i" }}</li>
                    {% if question.updated != question.published %}
                        <li>updated on {{ question.updated|date:"F d, Y" }} at {{ question.updated|date:"H:i" }}</li>
                    {% endif %}
                </div>
            </ul> 
        </li>
    </ul>
    <form class="form" action="{% url 'blog:question-delete' question.id %}" method="post">
        {% csrf_token %}
        <h4 class="form-title" style="margin-bottom: 0.5rem; margin-top: 0.75rem;">Are you sure that you want to delete the above question?</h4>
        <div class="form-buttons">
            <input class="button" type="submit" value="Delete">
            <a class="button" href="{% url 'blog:question-detail' question.id %}">Cancel</a> 
        </div>
    </form>
{% endblock content %}

project/blog/templates/blog/detail.html
{% extends "project/base.html" %}
{% load form_tags_filters %}

{% block content %}
    <ul class="questions-list">
        <li class="question-card">
            <h2 class="question-title">{{ question.title }}</h2>
            <p class="question-body">{{ question.body }}</p>
            <ul class="question-info">
                <div>
                    <li>asked by <a href="{% url 'user:profile' question.author.id %}" class="question-author">{{ question.author }}</a> on {{ question.published|date:"F d, Y" }} at {{ question.published|date:"H:i" }}</li>
                    {% if question.updated != question.published %}
                        <li>updated on {{ question.updated|date:"F d, Y" }} at {{ question.updated|date:"H:i" }}</li>
                    {% endif %}
                </div>
                <div>
                    <li><a href="{% url 'blog:question-edit' question.id %}">edit</a></li>
                    <li><a href="{% url 'blog:question-delete' question.id %}">delete</a></li>
                </div>
            </ul> 
        </li>
    </ul>
    {% block answer_add_form %}
    {% endblock answer_add_form %}
    <ul class="answers-list">
        <h3 class="answers-header">
            <div>
                {% if answers.count %}
                    {{ answers.count }} Answer{{ answers.count|pluralize }}
                {% else %}
                    0 Answers
                {% endif %}                
            </div>
            {% if answer_add_form == None %}
                <div>
                    <a href="{% url 'blog:answer-add' question.id %}" class="button" id="show-answer-add-form-button">Post Your Answer</a>
                </div>
            {% endif %}
        </h3>
        {% for answer in answers %}
            <li class="answer-card">
                <p class="answer-body">{{ answer.body }}</p>
                <ul class="answer-info"> 
                    <div>
                        <li>answered by <a href="{% url 'user:profile' answer.author.id %}" class="answer-author">{{ answer.author.username }}</a> on {{ answer.published|date:"F d, Y" }} at {{ answer.published|date:"H:i" }}</li>
                    </div>
                    <div>
                        <li><a href="{% url 'blog:answer-edit' question.id answer.id %}">edit</a></li>
                        <li><a href="{% url 'blog:answer-delete' question.id answer.id %}">delete</a></li>
                    </div>
                </ul>
            </li>
            {% block answer_edit_form %}
            {% endblock answer_edit_form %}

            {% block answer_delete_form %}
            {% endblock answer_delete_form %}
        {% endfor %}
    </ul>
{% endblock content %}

project/blog/templates/blog/edit.html
{% extends "project/base.html" %}
{% load form_tags_filters %}

{% block content %}
    <form class="form" action="{% url 'blog:question-edit' question.id %}" method="post">
        {% csrf_token %}
        <h2 class="form-title">Edit Your Question</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <ul>
            {% for field in question_ask_edit_form %}
                {% with field=field|label_suffix:'' %}
                    <li>
                        {% if field.id_for_label == 'id_title' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Choose a title for your question' }}
                        {% elif field.id_for_label == 'id_body' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Write your question' }}
                        {% endif %}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <div class="help-text">{{ field.help_text }}</div>
                        {% endif %}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
        <div class="form-buttons">
            <input class="button" type="submit" value="Update">
            <a class="button" href="{% url 'blog:question-detail' question.id %}">Cancel</a>
        </div>
    </form>
{% endblock content %}

project/blog/templates/blog/index.html
{% extends "project/base.html" %}

{% block content %}
    {% if questions_list %}
        <ul class="questions-list">
            {% for question in questions_list %}
                {% with answers=question.answer_set.all %}
                    <li class="question-card">
                        <h2 class="question-title"><a href="{% url 'blog:question-detail' question.id %}">{{ question.title }}</a></h2>
                        <p class="question-body-preview">{{ question.body }}</p>
                        <ul class="question-info">
                            <div>
                                <li>asked by <a href="{% url 'user:profile' question.author.id %}" class="question-author">{{ question.author }}</a> on {{ question.published|date:"F d, Y" }} at {{ question.published|date:"H:i" }}</li>
                                <li>
                                    {% if answers.count %}
                                        has {{ answers.count }} answer{{ answers.count|pluralize }} given by:
                                        {% for answer in answers %}
                                            {% if forloop.counter <= 3 %}
                                                {% if forloop.counter == answers.count %}
                                                    <a href="{% url 'user:profile' answer.author.id %}" class="answer-author">{{ answer.author.username }}</a>
                                                {% else %}
                                                    <a href="{% url 'user:profile' answer.author.id %}" class="answer-author">{{ answer.author.username }}</a>,
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                        {% if answers.count > 3 %}
                                            and others
                                        {% endif %}
                                    {% else %}
                                        has 0 answers
                                    {% endif %}
                                </li>
                            </div>
                        </ul>
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
    {% else %}
        <p class="empty-questions-list">No questions are available.</p>
    {% endif %}
{% endblock content %}

project/blog/templates/blog/permission_denied.html
{% extends "project/base.html" %}

{% block content %}
    <h3>You are not authorized to {{ operation }} this {{ model }}.</h3>
{% endblock content %}

project/blog/templates/blog/question_ask.html
{% extends "project/base.html" %}
{% load form_tags_filters %}

{% block content %}
    <form class="form" action="{% url 'blog:question-ask' %}" method="post">
        {% csrf_token %}
        <h2 class="form-title">Ask a New Question</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <ul>
            {% for field in question_ask_edit_form %}
                {% with field=field|label_suffix:'' %}
                    <li>
                        {% if field.id_for_label == 'id_title' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Choose a title for your question' }}
                        {% elif field.id_for_label == 'id_body' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Write your question' }}
                        {% endif %}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <div class="help-text">{{ field.help_text }}</div>
                        {% endif %}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
        <div class="form-buttons">
            <input class="button" type="submit" value="Post">
        </div>
    </form>
{% endblock content %}

project/blog/templates/blog/question_delete.html
{% extends "project/base.html" %}

{% block content %}
    <ul class="questions-list">
        <li class="question-card">
            <h2 class="question-title">{{ question.title }}</h2>
            <p class="question-body-preview">{{ question.body }}</p>
            <ul class="question-info">
                <div>
                    <li>asked by <span class="question-author">{{ question.author }}</span> on {{ question.published|date:"F d, Y" }} at {{ question.published|date:"H:i" }}</li>
                    {% if question.updated != question.published %}
                        <li>updated on {{ question.updated|date:"F d, Y" }} at {{ question.updated|date:"H:i" }}</li>
                    {% endif %}
                </div>
            </ul> 
        </li>
    </ul>
    <form class="form" action="{% url 'blog:question-delete' question.id %}" method="post">
        {% csrf_token %}
        <h4 class="form-title" style="margin-bottom: 0.5rem; margin-top: 0.75rem;">Are you sure that you want to delete the above question?</h4>
        <div class="form-buttons">
            <input class="button" type="submit" value="Delete">
            <a class="button" href="{% url 'blog:question-detail' question.id %}">Cancel</a> 
        </div>
    </form>
{% endblock content %}

project/blog/templates/blog/question_edit.html
{% extends "project/base.html" %}
{% load form_tags_filters %}

{% block content %}
    <form class="form" action="{% url 'blog:question-edit' question.id %}" method="post">
        {% csrf_token %}
        <h2 class="form-title">Edit Your Question</h2>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <ul>
            {% for field in question_ask_edit_form %}
                {% with field=field|label_suffix:'' %}
                    <li>
                        {% if field.id_for_label == 'id_title' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Choose a title for your question' }}
                        {% elif field.id_for_label == 'id_body' %}
                            {{ field.label_tag }}
                            {{ field|placeholder:'Write your question' }}
                        {% endif %}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <div class="help-text">{{ field.help_text }}</div>
                        {% endif %}
                    </li>
                {% endwith %}
            {% endfor %}
        </ul>
        <div class="form-buttons">
            <input class="button" type="submit" value="Update">
            <a class="button" href="{% url 'blog:question-detail' question.id %}">Cancel</a>
        </div>
    </form>
{% endblock content %}